/* Objects */
export const OBJECTS_RECEIVE = 'OBJECTS_RECEIVE';
export const OBJECTS_REQUEST = 'OBJECTS_REQUEST';
export const OBJECTS_DELETE = 'OBJECTS_DELETE';
export const OBJECTS_SELECT = 'OBJECTS_SELECT';
export const OBJECTS_UNSELECT = 'OBJECTS_UNSELECT';
export const OBJECTS_SELECT_ALL = 'OBJECTS_SELECT_ALL';
export const OBJECTS_SELECT_NONE = 'OBJECTS_SELECT_NONE';

/* Callbacks */
export const CALLBACKS_RECEIVE = 'CALLBACKS_RECEIVE';
export const CALLBACKS_REQUEST = 'CALLBACKS_REQUEST';

/* Reviews */
export const REVIEWS_RECEIVE = 'REVIEWS_RECEIVE';
export const REVIEWS_REQUEST = 'REVIEWS_REQUEST';
export const REVIEWS_DELETE = 'REVIEWS_DELETE';
export const REVIEWS_SELECT = 'REVIEWS_SELECT';
export const REVIEWS_UNSELECT = 'REVIEWS_UNSELECT';
export const REVIEWS_SELECT_ALL = 'REVIEWS_SELECT_ALL';
export const REVIEWS_SELECT_NONE = 'REVIEWS_SELECT_NONE';
