export const SHOW_ADD_CATALOG_ITEM_BUTTON = 'SHOW_ADD_CATALOG_ITEM_BUTTON';
export const HIDE_ADD_CATALOG_ITEM_BUTTON = 'HIDE_ADD_CATALOG_ITEM_BUTTON';

export const SELECT_ALL = 'SELECT_ALL';
export const SELECT_NONE = 'SELECT_NONE';

export const CLEAR_DATA = 'CLEAR_DATA';

export const RECEIVE_OBJECTS = 'RECEIVE_OBJECTS';
export const DELETE_OBJECTS = 'DELETE_OBJECTS';
export const TOGGLE_OBJECT_SELECT = 'TOGGLE_OBJECT_SELECT';
export const TOGGLE_OBJECT_HIDDEN = 'TOGGLE_OBJECT_HIDDEN';
export const ACTIVATE_ALL_SELECTED = 'ACTIVATE_ALL_SELECTED';
export const DEACTIVATE_ALL_SELECTED = 'DEACTIVATE_ALL_SELECTED';
