/* Objects */
export const OBJECTS_RECEIVE = 'OBJECTS_RECEIVE';
export const OBJECTS_REQUEST = 'OBJECTS_REQUEST';
export const OBJECTS_SELECT = 'OBJECTS_SELECT';
export const OBJECTS_UNSELECT = 'OBJECTS_UNSELECT';
export const OBJECTS_SELECT_ALL = 'OBJECTS_SELECT_ALL';
export const OBJECTS_SELECT_NONE = 'OBJECTS_SELECT_NONE';

/* Callbacks */
export const CALLBACKS_RECEIVE = 'CALLBACKS_RECEIVE';
export const CALLBACKS_REQUEST = 'CALLBACKS_REQUEST';
